apiVersion: v1
kind: Service
metadata:
    name: user-management-service
spec:
    selector:
        app: user-management-service
    ports:
        - protocol: "TCP"
          port: 8080
          targetPort: 8080
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: user-management-service
spec:
    selector:
        matchLabels:
            app: user-management-service
    replicas: 2
    template:
        metadata:
            labels:
                app: user-management-service
        spec:
            containers:
                - name: user-management-service
                  image: ninjakotka/user-management-service:latest
                  env:
                      - name: KAFKA_HOST
                        value: "10.1.0.111"
                      - name: KAFKA_PORT
                        value: "9092"
                      - name: DB_HOST
                        value: "10.1.0.105"
                      - name: DB_PORT
                        value: "3306"
                      - name: DB_NAME
                        value: "coinbase"
                      - name: DB_USERNAME
                        value: "root"
                      - name: DB_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: mysql-secret
                                key: password
                      - name: AUTH_HOST
                        value: "10.1.0.130"
                      - name: AUTH_PORT
                        value: "8090"
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8080
