apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - protocol: "TCP"
      port: 8091
      targetPort: 8091
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  selector:
    matchLabels:
      app: notification-service
  replicas: 2
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: ninjakotka/notification-service:latest
          env:
            - name: KAFKA_HOST
              value: "10.1.0.111"
            - name: KAFKA_PORT
              value: "9092"
            - name: SMTP_USERNAME
              value: "minicoinbase.auth@gmail.com"
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: smtp-secret
                  key: password
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091