apiVersion: v1
kind: Service
metadata:
    name: auth-service
spec:
    selector:
        app: auth-service
    ports:
        - protocol: "TCP"
          port: 8090
          targetPort: 8090
    type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: auth-service
spec:
    selector:
        matchLabels:
            app: auth-service
    replicas: 2
    template:
        metadata:
            labels:
                app: auth-service
        spec:
            containers:
                - name: auth-service
                  image: ninjakotka/auth-service:latest
                  env:
                      - name: REDIS_HOST
                        value: "10.99.49.38"
                      - name: REDIS_PORT
                        value: "6379"
                      - name: JWT_SECRET
                        value: "abcdefghijklmnOPQRSTUVWXYZ12321314fsdfsdhfdghfgh"
                  imagePullPolicy: IfNotPresent
                  ports:
                      - containerPort: 8090
